
-- Add sample businesses for Udupi
INSERT INTO businesses (name, category, city, address, phone, image_url, owner, created_at, approved, area, short_desc) VALUES
('Diana Restaurant', 'Eat', 'Udupi', 'Car Street, Udupi', '+91 98456 12345', 'https://media-cdn.tripadvisor.com/media/photo-s/0a/8b/2e/34/diana-restaurant.jpg', 'admin', CURRENT_TIMESTAMP, true, 'Car Street', 'Famous restaurant in Udupi serving authentic local cuisine and South Indian breakfast.'),
('Udupi Krishna Temple Prasadam', 'Eat', 'Udupi', 'Near Krishna Temple, Udupi', '+91 98456 54321', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGQ5lZGYYCUQF8dAV5B3sF2HQhyKy4jVHJTw&s', 'admin', CURRENT_TIMESTAMP, true, 'Temple Area', 'Sacred prasadam served near the famous Krishna Temple, authentic vegetarian meals.'),
('City Pharmacy Udupi', 'Health', 'Udupi', 'Court Road, Udupi', '+91 98456 78901', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPVL8mJLJBgdhHhmbHfSkjCVkEUG6Kk5dGJw&s', 'admin', CURRENT_TIMESTAMP, true, 'Court Road', 'Trusted pharmacy in Udupi with 24x7 service and wide range of medicines.'),
('Udupi Medicals', 'Health', 'Udupi', 'Service Bus Stand, Udupi', '+91 98456 11111', 'https://lh3.googleusercontent.com/gps-cs-s/AC9h4notUi_-pQU2enIj1hCUBIOcoM7m3rHGtTQ2QhfKvPR6M2OUS1UK9J74PukA-y2lYYjjiJlDXfOTiRnYbDg-QEScWwaOm6yBvbNbBooEvL72uB11T-NKVHAb0899pESR558MR5M=s1360-w1360-h1020-rw', 'admin', CURRENT_TIMESTAMP, true, 'Bus Stand', 'Popular medical store near bus stand providing quality medicines and health products.'),
('Udupi General Store', 'Shop', 'Udupi', 'Market Road, Udupi', '+91 98456 22222', 'https://content.jdmagicbox.com/comp/udupi/d4/0820px820.x820.210129110220.q2d4/catalogue/ganesh-bazaar-kundapura-udupi-supermarkets-qi2odb7z6x.jpg', 'admin', CURRENT_TIMESTAMP, true, 'Market Road', 'Well-stocked general store serving daily needs of Udupi residents.');

-- Add sample businesses for Manipal
INSERT INTO businesses (name, category, city, address, phone, image_url, owner, created_at, approved, area, short_desc) VALUES
('Dollops Restaurant', 'Eat', 'Manipal', 'Manipal Center, Manipal', '+91 98456 33333', 'https://media-cdn.tripadvisor.com/media/photo-s/0a/8b/2e/34/diana-restaurant.jpg', 'admin', CURRENT_TIMESTAMP, true, 'Manipal Center', 'Popular restaurant in Manipal serving continental and Indian cuisine for students and families.'),
('Pulse Pharmacy', 'Health', 'Manipal', 'Near MAHE, Manipal', '+91 98456 44444', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPVL8mJLJBgdhHhmbHfSkjCVkEUG6Kk5dGJw&s', 'admin', CURRENT_TIMESTAMP, true, 'MAHE Area', 'Student-friendly pharmacy near Manipal university with affordable medicines.'),
('Manipal Store', 'Shop', 'Manipal', 'Student Area, Manipal', '+91 98456 55555', 'https://content.jdmagicbox.com/comp/udupi/d4/0820px820.x820.210129110220.q2d4/catalogue/ganesh-bazaar-kundapura-udupi-supermarkets-qi2odb7z6x.jpg', 'admin', CURRENT_TIMESTAMP, true, 'Student Area', 'Convenient store for students with snacks, stationery, and daily essentials.'),
('Manipal Tiffin Center', 'Eat', 'Manipal', 'Tiger Circle, Manipal', '+91 98456 66666', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8uF8R-iUt5kJk2t6lJbCmZRjUJtkA9cXV5w&s', 'admin', CURRENT_TIMESTAMP, true, 'Tiger Circle', 'Affordable tiffin center popular among students for home-style vegetarian meals.');

-- Add sample businesses for Koteshwara
INSERT INTO businesses (name, category, city, address, phone, image_url, owner, created_at, approved, area, short_desc) VALUES
('Koteshwara Beach Resort', 'Stay', 'Koteshwara', 'Beach Road, Koteshwara', '+91 98456 77777', 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/524691400.jpg?k=b9f5a16f1fbef88fe71a67cca664fad4f9161e8311944b06bfa6df02586bc72a&o=&hp=1', 'admin', CURRENT_TIMESTAMP, true, 'Beach Road', 'Beautiful beach resort with comfortable rooms and sea view in Koteshwara.'),
('Koteshwara Clinic', 'Health', 'Koteshwara', 'Main Road, Koteshwara', '+91 98456 88888', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPVL8mJLJBgdhHhmbHfSkjCVkEUG6Kk5dGJw&s', 'admin', CURRENT_TIMESTAMP, true, 'Main Road', 'Local clinic providing basic healthcare services to Koteshwara residents.'),
('Beach View Cafe', 'Eat', 'Koteshwara', 'Near Beach, Koteshwara', '+91 98456 99999', 'https://i.ytimg.com/vi/iw1ja99LFDE/maxresdefault.jpg', 'admin', CURRENT_TIMESTAMP, true, 'Beach Area', 'Scenic cafe near Koteshwara beach serving fresh seafood and continental dishes.');
